# Generated by Django 3.0.7 on 2020-08-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DoubleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Double Jeopardy Category',
                'verbose_name_plural': 'Double Jeopardy Categories',
            },
        ),
        migrations.CreateModel(
            name='DoubleAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, default='', max_length=1000)),
                ('value', models.PositiveIntegerField(choices=[(400, '400'), (800, '800'), (1200, '1200'), (1600, '1600'), (2000, '2000')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.DoubleCategory')),
            ],
            options={
                'verbose_name': 'Double Jeopardy Answer',
                'verbose_name_plural': 'Double Jeopardy Answers',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, default='', max_length=1000)),
                ('value', models.PositiveIntegerField(choices=[(200, '200'), (400, '400'), (600, '600'), (800, '800'), (1000, '1000')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.Category')),
            ],
        ),
    ]
